#!/bin/bash
# Build Script - Compile Each Contract Individually
# Generated by Immunefi Instascope

set -e

echo "Building 11 contracts individually..."
echo ""

echo "Building USDeSilo (contract_USDeSilo_7fc7)"
FOUNDRY_PROFILE=contract_USDeSilo_7fc7 forge build || {
  echo "❌ Failed to build USDeSilo"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_USDeSilo_7fc7 forge build"
}
echo "✅ Built USDeSilo"
echo ""

echo "Building EthenaMinting (contract_EthenaMinting_2cc4)"
FOUNDRY_PROFILE=contract_EthenaMinting_2cc4 forge build || {
  echo "❌ Failed to build EthenaMinting"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_EthenaMinting_2cc4 forge build"
}
echo "✅ Built EthenaMinting"
echo ""

echo "Building EthenaLPStaking (contract_EthenaLPStaking_8707)"
FOUNDRY_PROFILE=contract_EthenaLPStaking_8707 forge build || {
  echo "❌ Failed to build EthenaLPStaking"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_EthenaLPStaking_8707 forge build"
}
echo "✅ Built EthenaLPStaking"
echo ""

echo "Building StakingRewardsDistributor (contract_StakingRewardsDistributor_f2fa)"
FOUNDRY_PROFILE=contract_StakingRewardsDistributor_f2fa forge build || {
  echo "❌ Failed to build StakingRewardsDistributor"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_StakingRewardsDistributor_f2fa forge build"
}
echo "✅ Built StakingRewardsDistributor"
echo ""

echo "Building ENA (contract_ENA_57e1)"
FOUNDRY_PROFILE=contract_ENA_57e1 forge build || {
  echo "❌ Failed to build ENA"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_ENA_57e1 forge build"
}
echo "✅ Built ENA"
echo ""

echo "Building StakedUSDeOFTAdapter (contract_StakedUSDeOFTAdapter_211c)"
FOUNDRY_PROFILE=contract_StakedUSDeOFTAdapter_211c forge build || {
  echo "❌ Failed to build StakedUSDeOFTAdapter"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_StakedUSDeOFTAdapter_211c forge build"
}
echo "✅ Built StakedUSDeOFTAdapter"
echo ""

echo "Building TransparentUpgradeableProxy (contract_TransparentUpgradeableProxy_8be3)"
FOUNDRY_PROFILE=contract_TransparentUpgradeableProxy_8be3 forge build || {
  echo "❌ Failed to build TransparentUpgradeableProxy"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_TransparentUpgradeableProxy_8be3 forge build"
}
echo "✅ Built TransparentUpgradeableProxy"
echo ""

echo "Building TransparentUpgradeableProxy (contract_TransparentUpgradeableProxy_c139)"
FOUNDRY_PROFILE=contract_TransparentUpgradeableProxy_c139 forge build || {
  echo "❌ Failed to build TransparentUpgradeableProxy"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_TransparentUpgradeableProxy_c139 forge build"
}
echo "✅ Built TransparentUpgradeableProxy"
echo ""

echo "Building USDtbMinting (contract_USDtbMinting_a3dd)"
FOUNDRY_PROFILE=contract_USDtbMinting_a3dd forge build || {
  echo "❌ Failed to build USDtbMinting"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_USDtbMinting_a3dd forge build"
}
echo "✅ Built USDtbMinting"
echo ""

echo "Building StakedENA (contract_StakedENA_7fd5)"
FOUNDRY_PROFILE=contract_StakedENA_7fd5 forge build || {
  echo "❌ Failed to build StakedENA"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_StakedENA_7fd5 forge build"
}
echo "✅ Built StakedENA"
echo ""

echo "Building AnchorageTokenUSDtb (contract_AnchorageTokenUSDtb_9d6d)"
FOUNDRY_PROFILE=contract_AnchorageTokenUSDtb_9d6d forge build || {
  echo "❌ Failed to build AnchorageTokenUSDtb"
  echo "   You can debug with: FOUNDRY_PROFILE=contract_AnchorageTokenUSDtb_9d6d forge build"
}
echo "✅ Built AnchorageTokenUSDtb"
echo ""

echo "================================"
echo "Build complete - each contract compiled independently"
echo "================================"
